#!/bin/bash

# application-specific master shell script called by workflow launcher
# organizes a set of serial pipeline steps, with staged execution

# !!! IMPORTANT !!!
# command 'analyze' requires _manual_editing_ of cell marks
# in the RData file generated by command 'bin'
# otherwise, the script will fail with no cells to use
# !!! IMPORTANT !!!

# always call this support script first
source $PIPELINE_DIR/_workflow/workflow.sh

# re-parse CellRanger bam data into variable-width bins based on accepted cells only
runWorkflowStep 1 rebin/rebin.sh

# apply further steps to clean up bin x cell matrix and normalize cell baselines for drift
runWorkflowStep 2 normalize/normalize.sh 

# find 1st-pass CNVs by scanning genome in windows, using bin metrics independent of cell clustering
#runWorkflowStep 3 scan/scan.sh            

