
# !!! IMPORTANT !!!
# command 'genotype' requires _manual_editing_ of cell marks
# in the RData file generated by command 'bin'
# otherwise, the script will fail with no cells to use
# !!! IMPORTANT !!!

# always call this support script first
source $PIPELINE_DIR/_workflow/workflow.sh

# re-parse CellRanger bam data into variable-width bins based on accepted cells only
runWorkflowStep 1 genotype/genotype.sh


